development:
  cdn_base_url: http://localhost:3000/static
  photos_base_url: http://localhost:3000/photos
  photos_folder_path: /Users/saurav/dev/data/jukebox/photos
  artwork_base_url: http://localhost:3000/artworks
  artwork_folder_path: /Users/saurav/dev/data/jukebox/artworks
  media_base_url: http://localhost:3000/media
  media_folder_path: /Users/saurav/dev/data/jukebox/media

test:
  photos_base_url: http://localhost:3000/photos
  photos_folder_path: /Users/saurav/dev/data/jukebox/photos
  cdn_base_url: http://cn/wkt/static  
  artwork_base_url: http://localhost:3000/artworks
  artwork_folder_path: /Users/saurav/dev/data/jukebox/artworks
  media_base_url: http://localhost:3000/media
  media_folder_path: /Users/saurav/dev/data/jukebox/media

staging:
  photos_base_url: http://localhost:3000/photos
  photos_folder_path: /Users/saurav/dev/data/jukebox/photos
  cdn_base_url: http://staging/static
  artwork_base_url: http://localhost:3000/artworks
  artwork_folder_path: /Users/saurav/dev/data/jukebox/artworks
  media_base_url: http://localhost:3000/media
  media_folder_path: /Users/saurav/dev/data/jukebox/media

production:
  photos_base_url: http://localhost:3000/photos
  photos_folder_path: /Users/saurav/dev/data/jukebox/photos
  cdn_base_url: http://production/static
  artwork_base_url: http://localhost:3000/artworks
  artwork_folder_path: /Users/saurav/dev/data/jukebox/artworks
  media_base_url: http://localhost:3000/media
  media_folder_path: /Users/saurav/dev/data/jukebox/media
